controller_list:
  - name: trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
  - name: gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - robotiq_85_left_knuckle_joint
